"""add phone_verifications

Revision ID: ebadec36dec7
Revises: bd97486c88b5
Create Date: 2026-04-21 15:02:03.305040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebadec36dec7'
down_revision: Union[str, None] = 'bd97486c88b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_verifications_phone_number'), ['phone_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_verifications_phone_number'))

    op.drop_table('phone_verifications')
    # ### end Alembic commands ###
