"""add_fixed_status_and_hosting_updated_at

Revision ID: 5dc9e08a8fd0
Revises: ebadec36dec7
Create Date: 2026-04-22 17:32:21.989676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc9e08a8fd0'
down_revision: Union[str, None] = 'ebadec36dec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # PostgreSQL: Enum 타입에 FIXED 값 추가 (SQLite는 VARCHAR라 불필요)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TYPE hostingstatus ADD VALUE IF NOT EXISTS '확정'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # PostgreSQL: Enum 값 제거는 지원하지 않으므로 updated_at만 롤백
    with op.batch_alter_table('hostings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True)
